# Generated by Django 3.2.5 on 2021-08-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210730_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditableFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=80)),
                ('field_title', models.CharField(max_length=255)),
                ('field_url', models.URLField(default='http://', max_length=255)),
                ('field_content', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='uploaded')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='blog'),
        ),
    ]
