# Generated by Django 3.2.5 on 2021-08-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210824_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='SociaLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(default='http://', max_length=255)),
            ],
        ),
    ]
