# Generated by Django 3.2.5 on 2021-08-25 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_socialinks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
