# Generated by Django 3.2.5 on 2021-08-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210825_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
