# Generated by Django 3.2.5 on 2021-08-25 13:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_ipmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40)),
                ('session', models.CharField(max_length=40)),
                ('created', models.DateTimeField(default=datetime.datetime(2021, 8, 25, 13, 54, 46, 619464))),
            ],
        ),
        migrations.DeleteModel(
            name='IpModel',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hit_count_fake',
        ),
        migrations.AddField(
            model_name='postviews',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_views', to='blog.post'),
        ),
    ]
