# Generated by Django 4.1.2 on 2022-10-16 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210825_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postviews',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 8, 34, 38, 493426)),
        ),
        migrations.AlterField(
            model_name='postviews',
            name='session',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
